/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    CustomerAddress: typeof import('./src/components/CustomerAddress.vue')['default']
    FormError: typeof import('./src/components/FormError.vue')['default']
    IconBack: typeof import('./src/components/icons/IconBack.vue')['default']
    IconCheck: typeof import('./src/components/icons/IconCheck.vue')['default']
    IconDelete: typeof import('./src/components/icons/IconDelete.vue')['default']
    IconDetails: typeof import('./src/components/icons/IconDetails.vue')['default']
    IconEdit: typeof import('./src/components/icons/IconEdit.vue')['default']
    IconInfo: typeof import('./src/components/icons/IconInfo.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconPost: typeof import('./src/components/icons/IconPost.vue')['default']
    IconTicket: typeof import('./src/components/icons/IconTicket.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
